from turtle import *

def flying_colors():
    color("red")
    circle(115, steps = 8)
    color("blue")
    circle(105, steps = 8)
    color("red")
    circle(95, steps = 8)
    color("blue")
    circle(85, steps = 8)
    color("red")
    circle(75, steps = 8)
    color("blue")
    circle(65, steps = 8)
    color("red")
    circle(55, steps = 8)
    color("blue")
    circle(45, steps = 8)
    color("red")
    circle(35, steps = 8)
    color("blue")
    circle(25, steps = 8)
    color("red")
    circle(15, steps = 8)
    color("blue")
    circle(5, steps = 8)
    color("red")
    circle(115, steps = 4)
    color("blue")
    circle(105, steps = 4)
    color("red")
    circle(95, steps = 4)
    color("blue")
    circle(85, steps = 4)
    color("red")
    circle(75, steps = 4)
    color("blue")
    circle(65, steps = 4)
    color("red")
    circle(55, steps = 4)
    color("blue")
    circle(45, steps = 4)
    color("red")
    circle(35, steps = 4)
    color("blue")
    circle(25, steps = 4)
    color("red")
    circle(15, steps = 4)
    color("blue")
    circle(5, steps = 4)
    color("red")
flying_colors()

